version: '3.9'
services:
  web:
    image: traggo/server:latest
    container_name: traggo
    restart: always
    ports:
      - ${APP_PORT}:3030
    networks:
      - default
    volumes:
      - ./traggodata:/opt/traggo/data
    environment:
      TRAGGO_DEFAULT_USER_NAME: ${APP_USER}
      TRAGGO_DEFAULT_USER_PASS: ${APP_PASS}

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
